### ISSUE TITLE
storybook not working

### ISSUE THREAD

**Issue by ritz078** [deptno/nextjs-typescript-boilerplate#14]
There are multiple issues in running it. Can you once try to run it?

1. ts-loader is not present in package.json.
2. once i install it.

```
WARNING in ./stories/index.stories.tsx
Module build failed: Error: You may be using an old version of webpack; please check you're using at least version 4
    at successfulTypeScriptInstance (/Users/ritz078/projects/next.js-typescript-starter-kit/node_modules/ts-loader/dist/instances.js:168:15)
    at Object.getTypeScriptInstance (/Users/ritz078/projects/next.js-typescript-starter-kit/node_modules/ts-loader/dist/instances.js:51:12)
    at Object.loader (/Users/ritz078/projects/next.js-typescript-starter-kit/node_modules/ts-loader/dist/index.js:16:41)
 @ ./stories .stories.tsx$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js
```

**Comment by deptno** [comment]
I'll check it tomorrow.
